### ISSUE TITLE
Finish Ramen Scope prototype

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Science-2024#2]
make more 3d printable, Add radius to corners and make walls .8mm thick. add hole for laser to poke through. add lid to make no light get in

**Comment by tommytn54** [comment]
Updated CAD, Window radius has been increased to 12.5

**Comment by tommytn54** [comment]
Updated CAD, revised terminology, window slot diameter and thickness increased

**Comment by tommytn54** [comment]
Updated CAD, revised terminology, window slot diameter and thickness increased

**Comment by tommytn54** [comment]
Updated CAD, revised terminology, window slot diameter and thickness increased
